baseURL: "https://abheaks.github.io/"
languageCode: "en-us"
title: "Profile"
theme: "hugo-profile-master"
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

#  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
#  customMenus:
#    - name: "Blog"
#      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/abhijiths.jpg"
  name: "Abhijith S"
  namecolor: ffc107
  profession: "Microsoft Dynamics CRM Developer"
  github: "https://github.com/abheaks"
#  gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/abheaks/"
  twitter: "https://twitter.com/abheaks"
#  instagram: "https://instagram.com/"
#  facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Microsoft Dynamics CRM developer with 2 years of experience inthe entire software development  life  cycle.  Proven  skills  in  interacting  with  businesses  to  meet  the requirements  and  develop  features.  I  am  a  collaborative  team  player,  an  effective communicator,   self-motivated   and   driven   with   strong   time   management   and prioritization abilities."
  #descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"
  skills:
    - name: C#
      percentage: 70
    - name: JavaScript
      percentage: 60
    - name: Alteryx
      percentage: 60
    - name: QlikView
      percentage: 60
#    - name: Power Automate
#       percentage: 60

  # Experience
  disable_experience: false
  experience:
    - company: "Ford Motor Company"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Nov 2019
      enddate: present
      featuredpoints:
        - point: Microsoft Dynamics CRM developer.
        - point: Developed Plugins, Workflows ,Customizations for Platform and Portal.
#    - company: "Facebook"
#      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
#      role: "Fullstack developer"
#      startdate: Mar 2020
#      enddate: Dec 2020
#      featuredpoints:
#       - point: Lead backend developer for a product.
#        - point: Created a frontend design for a product.
#    - company: "Amazon"
 #     # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
 #     role: "Fullstack developer"
#      startdate: Feb 2019
#      enddate: Jan 2020
#      featuredpoints:
#        - point: Lead backend developer for a product.
#        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "Bachelor of Technology"
      branch: "Electrical and Electronics"
      university: "Mar Athanasius Collage of Engineering Kothamangalam"
      startedyear: "2015"
      graduation: "2019"
    - degree: "Higher Secondary Education"
      branch: "Computer Science"
      university: "Technical Higher Secondary School, Perinthalmanna "
      startedyear: "2013"
      graduation: "2015"
    - degree: "High School"
      university: "Technical Higher Secondary School, Perinthalmanna "
      startedyear: "2014"
      graduation: "2015"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "abheaks.007@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: true
